name = input("Enter Your name:") 
university = input("Enter Your school: ") 
age = int(input("Enter Your age: "))
level = int(input("Enter Your level: "))
course = input("Enter Your course: ")
current_year = int(input("Enter Your Current year: ")) 
course_years = int(input("Enter Course years: "))
carrier = input("Enter Your carrier: ")
years_left = course_years - current_year

print("===========Student Profile========\n\n\n")
print("==================================")
print("Name: ", name, " Age: ", age)
print("==================================") 
print("School: ", university, "| level: ", level)
print("==================================")
print("Course: ", course )
print("==================================")
print("Course Years: ", course_years)
print("==================================")
print("Years Left: ", years_left)
print("==================================")
print("===carrier===", carrier)
print("==================================")
print(type(name))
